# Pytorch 튜토리얼

- 텐서는 배열이나, 행렬과 매우 유사한 특수한 자료구조이다.
- Pytorch에서는 이 텐서를 사용하여 모델의 입력과 출력 그리고 모델의 매개변수를 부호화(encode) 한다.
- Numpy의 ndarray와 유사하다.

In [2]:
import torch
import numpy as np

## 텐서 초기화
- 텐서는 여러가지 방법으로 초기화할 수 있다.

### 데이터로부터 직접 생성하기
- 데이터로부터 직접 텐서를 생성할 수 있다.
- 데이터의 자료형은 자동으로 유추된다.

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

###  Numpy 배열로부터 생성하기
- 텐서 -> Numpy, Numpy -> 텐서로 변환이 자유롭다.

In [4]:
# 리스트를 numpy array로 변환
np_array = np.array(data)
# numpy array를 tensor로 변환
np_to_ts = torch.from_numpy(np_array)
# tensor를 numpy array로 변환
ts_to_np = np.array(np_to_ts)
np_array, np_to_ts, ts_to_np

(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]]),
 array([[1, 2],
        [3, 4]]))

### 다른 텐서로부터 생성하기
- 명시적으로 재정의하지 않는다면, 인자로 주어진 텐서의 속성(모양, 자료형)을 유지한다.

In [8]:
x_ones = torch.ones_like(x_data)  # x_data의 속성을 유지
print(f'Ones Tensor: \n {x_ones} \n')
x_rand = torch.rand_like(x_data, dtype=torch.float)  # x_data의 속성을 덮어씀
print(f'Random Tensor: \n {x_rand} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5327, 0.0616],
        [0.1930, 0.3661]]) 



### 무작위 또는 상수 값 사용하기

In [9]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.6135, 0.4166, 0.4727],
        [0.4559, 0.7690, 0.7905]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [10]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
print(f'First row: {tensor[0]}')
print(f'First column: {tensor[:, 0]}')

First row: tensor([1., 0., 1., 1.])
First column: tensor([1., 1., 1., 1.])


In [13]:
print(f'Last column: {tensor[:, -1]}')

Last column: tensor([1., 1., 1., 1.])


In [16]:
tensor[:, -1] = 3
tensor[-1, :] = 4
tensor

tensor([[1., 0., 1., 3.],
        [1., 0., 1., 3.],
        [1., 0., 1., 3.],
        [4., 4., 4., 4.]])

In [17]:
print(f'Last column: {tensor[:, -1]}')

Last column: tensor([3., 3., 3., 4.])


In [18]:
print(f'Last column: {tensor[..., -1]}')

Last column: tensor([3., 3., 3., 4.])


### 텐서 조작 합치기
cat vs stack

In [26]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
t2 = torch.tensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
t2

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [28]:
t3 = torch.tensor([[19, 20, 21], [22, 23, 24], [25, 26, 27]])
t3

tensor([[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]])

In [32]:
cat1 = torch.cat([t1, t2, t3], dim=-2)
cat1

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]])

In [34]:
cat2 = torch.cat([t1, t2, t3], dim=0)
cat2

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]])

In [35]:
cat3 = torch.cat([t1, t2, t3], dim=-1)
cat3

tensor([[ 1,  2,  3, 10, 11, 12, 19, 20, 21],
        [ 4,  5,  6, 13, 14, 15, 22, 23, 24],
        [ 7,  8,  9, 16, 17, 18, 25, 26, 27]])

In [36]:
cat4 = torch.cat([t1, t2, t3], dim=1)
cat4

tensor([[ 1,  2,  3, 10, 11, 12, 19, 20, 21],
        [ 4,  5,  6, 13, 14, 15, 22, 23, 24],
        [ 7,  8,  9, 16, 17, 18, 25, 26, 27]])

In [37]:
stack1 = torch.stack([t1, t2, t3], dim=0)
stack1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [40]:
print(f'stack: {stack1.shape}')
print(f'cat: {cat2.shape}')

stack: torch.Size([3, 3, 3])
cat: torch.Size([9, 3])
